version: '3'


services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: pandas nltk pyarrow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./datalake_bronze:/opt/airflow/datalake_bronze
      - ./datalake_silver:/opt/airflow/datalake_silver
      - ./datalake_gold:/opt/airflow/datalake_gold
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: pandas nltk pyarrow	
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./datalake_bronze:/opt/airflow/datalake_bronze
      - ./datalake_silver:/opt/airflow/datalake_silver
      - ./datalake_gold:/opt/airflow/datalake_gold
    command: scheduler

